title: Portfolio
default_lang: fr
author:
  name: 'Antoine Tournepiche'
taxonomies:
  - category
  - tag
metadata:
  description: 'Le portfolio d''Antoine Tournepiche, étudiant en 2ème année de BTS SIO'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
